# this is a reference file for how to use the image hosted on GitHub Container Registry

version: "3.8"
services:
  nginx-custom:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
