services:
  ja4-nginx:
    build:
      context: ../
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../nginx_utils/nginx.conf:/etc/nginx/conf/nginx.conf
      - ../nginx_utils/server.crt:/etc/nginx/conf/server.crt
      - ../nginx_utils/server.key:/etc/nginx/conf/server.key
      - ../nginx_utils/logs:/etc/nginx/logs