name: Integration Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Start nginx with Docker Compose
        run: docker compose up --build -d

      - name: Run pytest
        run: pytest
