#!/bin/sh
# Regenerate the committed libbpf skeleton, ngx_ebpf.skel.h, which embeds
# the compiled BPF programs. Building nginx does not run this: it only needs
# libbpf. Run it after changing bpf/ngx_ebpf.bpf.c or ngx_ebpf.h, and commit
# the result.
#
#   sh ebpf/gen-skel.sh           regenerate (needs clang, bpftool and
#                                 kernel BTF)
#   sh ebpf/gen-skel.sh --check   fail if the skeleton is stale (needs only
#                                 sha256sum)
#
# The object is CO-RE: vmlinux.h is used only while compiling, and libbpf
# relocates field accesses for the running kernel at load time, so one
# skeleton serves every supported kernel.

set -eu

src=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
skel="$src/ngx_ebpf.skel.h"

# Part of the hash: changing the flags also makes the skeleton stale.
flags="-g -O2 -mcpu=v3 -target bpf -Wall -Werror"


inputs_hash() {
    { cat "$src/bpf/ngx_ebpf.bpf.c" "$src/ngx_ebpf.h"; printf '%s\n' "$flags"; } \
        | sha256sum | cut -d ' ' -f 1
}


if [ "${1:-}" = "--check" ]; then
    want=$(inputs_hash)
    have=$(sed -n 's/^ \* inputs-sha256: \([0-9a-f]*\)$/\1/p' "$skel" 2>/dev/null)

    if [ "$have" != "$want" ]; then
        echo "ebpf/ngx_ebpf.skel.h is stale: run sh ebpf/gen-skel.sh" >&2
        exit 1
    fi

    exit 0
fi

if [ $# -ne 0 ]; then
    echo "usage: sh ebpf/gen-skel.sh [--check]" >&2
    exit 2
fi


pick() {
    for tool in "$@"; do
        if command -v "$tool" >/dev/null 2>&1; then
            echo "$tool"
            return
        fi
    done
    echo "$1"
}

clang=${BPF_CLANG:-$(pick clang-18 clang)}
bpftool=${BPFTOOL:-bpftool}

# A fixed-length work path, not $TMPDIR: its length, though not its name,
# changes clang's type order and so the output.
tmp=$(mktemp -d /tmp/ngx_ebpf.XXXXXXXXXX)
trap 'rm -rf "$tmp"' EXIT

"$bpftool" btf dump file "${BPF_BTF:-/sys/kernel/btf/vmlinux}" format c \
    > "$tmp/vmlinux.h"

# Compile a copy of the inputs by relative paths only, so the output does not
# depend on where the checkout lives or where the script runs from: absolute
# paths change clang's type order, and the source-line text embedded in the
# BTF line info is read back through the recorded (relative) file name.
mkdir "$tmp/bpf"
cp "$src/bpf/ngx_ebpf.bpf.c" "$tmp/bpf/"
cp "$src/ngx_ebpf.h" "$tmp/"

(
    cd "$tmp"
    "$clang" $flags -fdebug-compilation-dir=. -I. \
        -c bpf/ngx_ebpf.bpf.c -o ngx_ebpf.tmp.o
)

# The BPF static linker drops DWARF (~0.9 MB) and keeps the .BTF and .BTF.ext
# sections that CO-RE needs.
"$bpftool" gen object "$tmp/ngx_ebpf.bpf.o" "$tmp/ngx_ebpf.tmp.o"

"$bpftool" gen skeleton "$tmp/ngx_ebpf.bpf.o" name ngx_ebpf > "$tmp/skel.h"

hash=$(inputs_hash)

awk -v hash="$hash" '
    { print }
    /THIS FILE IS AUTOGENERATED BY BPFTOOL/ && !done {
        print "/*"
        print " * Generated by ebpf/gen-skel.sh from bpf/ngx_ebpf.bpf.c and ngx_ebpf.h."
        print " * Do not edit; rerun the script after changing either file."
        print " * inputs-sha256: " hash
        print " */"
        done = 1
    }
' "$tmp/skel.h" > "$tmp/skel.out"

grep -q "inputs-sha256: $hash" "$tmp/skel.out" \
    || { echo "gen-skel.sh: bpftool header not found" >&2; exit 1; }

mv "$tmp/skel.out" "$skel"
echo "wrote $skel ($(wc -c < "$tmp/ngx_ebpf.bpf.o") byte object)"
